### PR TITLE
Removing dependency on old ncdf library

### PR DESCRIPTION
**Pull request by aukkola**
Replaced remaining ncdf commands with ncdf4 commands. Also removed ncdf package from package description file.

### CODE REVIEW

**Comment by naught101** [comment]
Thanks Anna,

I'm not sure that all of the other usage is safe (e.g. https://github.com/aukkola/palsR/blob/f5adfbdcb02b1e954b7c326226aba135872fabcc/R/BenchmarkEmpirical.R#L130), but I did check other files that use the new library, and they do seem to use the same format. If it does create bugs, fixes shouldn't be too hard to figure out.

**Comment by aukkola** [comment]
Yep, I checked some of the usage but probably missed that particular one. I’ll check through it again

On 14 Feb 2017, at 6:45 am, naught101 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Anna,

I'm not sure that all of the other usage is safe (e.g. https://github.com/aukkola/palsR/blob/f5adfbdcb02b1e954b7c326226aba135872fabcc/R/BenchmarkEmpirical.R#L130), but I did check other files that use the new library, and they do seem to use the same format. If it does create bugs, fixes shouldn't be too hard to figure out.

**Comment by naught101** [comment]
No, I think that one is OK, because (as far as I could see) it's the same syntax in both libraries. But there might be others that aren't

**Comment by aukkola** [comment]
I tested the syntaxes I could find and they seem to work with ncdf4. Possible I missed something though

**Comment by naught101** [comment]
Should be good then :)

**Pull request merged**
